In [1]:
import numpy as np

In [2]:
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0,1,1,0]]).T
x.shape,y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    return 1/(1+np.exp(-z))

In [4]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

In [14]:
#one hidden layer weights
wh=2*np.random.random((2,2))-1
bh=2*np.random.random((1,2))-1
wo=2*np.random.random((2,1))-1
bo=2*np.random.random((1,1))-1


In [18]:
#forward propagation with one hidden layer
lr=.5
for iter in range(10000):
    output0=x
    inputHidden=np.dot(output0,wh)+bh
    outputHidden=sig(inputHidden)
    inputForOutputLayer=np.dot(outputHidden,wo)+bo
    output=sig(inputForOutputLayer)

    first_term_output_layer=output-y
    second_term_output_layer=derivativeSig(inputForOutputLayer)
    first_two_output_layer=first_term_output_layer*second_term_output_layer

    first_term_hidden_layer=np.dot(first_two_output_layer,wo.T)
    second_term_hidden_layer=derivativeSig(inputHidden)
    first_two_hidden_layer=first_term_hidden_layer*second_term_hidden_layer

    changes_output=np.dot(outputHidden.T,first_two_output_layer)
    changes_output_bias=np.sum(first_two_output_layer,axis=0,keepdims=True)

    changes_hidden=np.dot(output.T,first_two_hidden_layer)
    changes_hidden_bias=np.sum(first_two_hidden_layer,axis=0,keepdims=True)

    wo=wo-lr*changes_output
    bo=bo-lr*changes_output_bias

    wh=wh-lr*changes_hidden
    bh=bh-lr*changes_hidden_bias

output0=x
inputHidden=np.dot(output0,wh)+bh
outputHidden=sig(inputHidden)
inputForOutputLayer=np.dot(outputHidden,wo)+bo
output=sig(inputForOutputLayer)
output,wh,bh,wo,bo  

                                

(array([[0.03106018],
        [0.65415572],
        [0.67597801],
        [0.66629314]]),
 array([[-6.63140263, -0.37205732],
        [-7.64122344,  0.34333963]]),
 array([[0.45548079, 1.72992818]]),
 array([[-6.74489078],
        [-1.15093879]]),
 array([[1.66481411]]))