In [1]:
import numpy as np
from sklearn import preprocessing

In [2]:
x=np.array([[1,1,1],
           [2,2,2],
           [3,3,3]])

In [3]:
x_scaled=preprocessing.scale(x)

In [4]:
x_scaled.mean(axis=0)

array([0., 0., 0.])

In [5]:
x_scaled.std(axis=0)

array([1., 1., 1.])

In [8]:
scaler=preprocessing.StandardScaler()
scaler.fit(x)

scaler.transform(x)

array([[-1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487]])

In [10]:
x_test=[[1,2,3]]
scaler.transform(x_test)

array([[-1.22474487,  0.        ,  1.22474487]])