In [1]:
import numpy as np

In [2]:
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0,0,0,1]]).T

x.shape,y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    return 1/(1+np.exp(-z))

In [4]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

In [5]:
#no hidden layer weights
weights=2*np.random.random((2,1))-1 # range is from -1 to 1
bias=2*np.random.random(1)-1 
weights,bias

(array([[-0.14856591],
        [-0.82865281]]),
 array([0.77988154]))

In [6]:
#forward propagation without any hidden layer
output0=x
output=sig(np.dot(output0,weights)+bias)
output

array([[0.68565458],
       [0.4878096 ],
       [0.65278772],
       [0.45082518]])

In [7]:
#hidden layer and output weights
wh=2*np.random.random((2,2))-1
bh=2*np.random.random((1,2))-1
wo=2*np.random.random((2,1))-1
bo=2*np.random.random((1,1))-1

In [8]:
output0=x
outputHidden=sig(np.dot(output0,wh)+bh)
output=sig(np.dot(outputHidden,wo)+bo)
output

array([[0.65423539],
       [0.6125644 ],
       [0.64160072],
       [0.60125586]])

In [9]:
#forward propagation without hidden layer
lr=0.1
for iter in range(10000):
    output0=x
    output=sig(np.dot(output0,weights)+bias)
    
    #Now we are doing backward propagation
    first_term=output-y
    input_for_last_layer=np.dot(output0,weights)+bias
    second_term=derivativeSig(input_for_last_layer)
    first_two=first_term*second_term
    
    changes=np.array([[0.0],[0.0]])
    for i in range(2):
        for j in range(4):
            changes[i][0]+=first_two[j][0]*output0[j][i]
    weights=weights-lr*changes
    bias_change=0.0
    for j in range(4):
        bias_change+=first_two[j][0]*1
    bias=bias-lr*bias_change
output=sig(np.dot(x,weights)+bias)
weights,bias,output

(array([[5.46833556],
        [5.46833555]]),
 array([-8.29524487]),
 array([[2.49639036e-04],
        [5.58872507e-02],
        [5.58872511e-02],
        [9.33480581e-01]]))

In [10]:
#forward propagation without hidden layer
lr=0.1
for iter in range(10000):
    output0=x
    output=sig(np.dot(output0,weights)+bias)
    
    #Now we are doing backward propagation
    first_term=output-y
    input_for_last_layer=np.dot(output0,weights)+bias
    second_term=derivativeSig(input_for_last_layer)
    first_two=first_term*second_term
    
    changes=np.dot(output0.T,first_two)
    weights=weights-lr*changes
    bias_change=np.sum(first_two)
    bias=bias-lr*bias_change
output=sig(np.dot(x,weights)+bias)
weights,bias,output

(array([[6.26813253],
        [6.26813253]]),
 array([-9.49202954]),
 array([[7.54451248e-05],
        [3.82762734e-02],
        [3.82762735e-02],
        [9.54533004e-01]]))