In [1]:
import numpy as np
li_arr=[i for i in range(0,100)]
np_arr=np.arange(100)
print(li_arr)
print(np_arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [2]:
print(np_arr.itemsize)
print(np_arr.itemsize*np_arr.size)

4
400


In [4]:
import sys
a=10
print(sys.getsizeof(a))
print(sys.getsizeof(1)*len(li_arr))

28
2800


In [7]:
import time
size=100000
def add_list():
    t1=time.time()
    a=range(size)
    b=range(size)
    c=[a[i]+b[i] for i in range(size)]
    t2=time.time()
    return (t2-t1)

def add_np_arr():
    t1=time.time()
    a=np.arange(size)
    b=np.arange(size)
    c=a+b
    t2=time.time()
    return (t2-t1)

t_list=add_list()
t_numpy=add_np_arr()
print("List=",t_list*1000)
print("numpy=",t_numpy*1000)

List= 15.07258415222168
numpy= 0.0


In [8]:
#Advantanges:-
#Less time
#Lss memory
#Convenience
#Functionality
#numpy takes less time because it does not operate element-wise rather it operates chunk wise with the help of concept,Vectorization
#numpy is written in using C and Fortran language which makes it fast and easy to use

In [10]:
a=np.arange(10)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a=np.arange(2,10)
a

array([2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a=np.arange(2,10,2)
a

array([2, 4, 6, 8])

In [15]:
#In case of np.arange we can put start, end and the gap; here end point is not inclusive

In [19]:
#By default int generates 50 values in the range
b=np.linspace(2,10)
b
print(b[2]-b[1])
print(b[3]-b[2])

0.16326530612244872
0.16326530612244916


In [21]:
#Here it takes start, end  and the no of samples,here end point is inclusive by default
b=np.linspace(2,10,5,dtype=int,endpoint=False)
b

array([2, 3, 5, 6, 8])

In [23]:
#here we can use only nxn matrix
c=np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
#here we can use mxn matrix
d=np.eye(3,4)
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [27]:
e=np.random.rand(3)
e

array([0.42872254, 0.59804746, 0.72416491])

In [30]:
f=np.random.rand(3,4)*10
f

array([[5.70405203, 7.61303697, 2.03483793, 8.39561999],
       [3.65232071, 6.8543136 , 4.36803972, 7.09921482],
       [8.4065129 , 0.38161558, 3.4963031 , 2.74065315]])

In [36]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [37]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(5,)
int32
(4,)


In [39]:
print(arr[3])

3


In [40]:
print(arr[0:2])

[0 1]


In [3]:
import numpy as np
x=np.random.randint(1,20,8)
x

array([ 8,  2, 11, 15,  1, 16, 18,  6])

In [5]:
bool_arr=x>12
bool_arr

array([False, False, False,  True, False,  True,  True, False])

In [7]:
new_arr=x[(x>8)&(x<18)]
new_arr

array([11, 15, 16])

In [11]:
ind=np.where(x!=12)
print(ind)
print(x[ind])


(array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64),)
[ 8  2 11 15  1 16 18  6]


In [ ]:
#Broadcasting happens when we do arithmetic operation on matrix of different sizes